#!/bin/sh

LOGFILE="l2s-billeder.log"

source ~/ddsync/settings.txt

echo -e "\n\n" >> $LOGFILE
date +%Y-%m-%dT%H:%M:%S%z >> $LOGFILE
echo -e "\n\n" >> $LOGFILE

rsync -rltzPhO "$DATAFOLDER/Billeder" ${DDUSER,,}@vae.danishdecoration.dk:/tank/dd/share/ | tee -a $LOGFILE

echo -e "\n\n" >> $LOGFILE

echo "Afsluttet. Venter i 20 sekunder"
sleep 20
